### ISSUE TITLE
[Feature request] Option to freeze entire screen on click for selection

### ISSUE THREAD

**Issue by rieje** [emersion/slurp#100]
Simple feature request: provide an option to freeze entire "screen" on click for selection. This is the behavior of many screenshot tools, allowing the user to easily select region of an animated screen for the perfect frame (e.g. a video or constantly changing data).

As soon as the user presses mouse button for selection, the entire screen "freezes", allowing you to adjust your selection region.

**Comment by emersion** [comment]
This would require doing screen capture inside slurp. This is out of scope.

**Comment by tmccombs** [comment]
For the "freeze" feature you would need to basically capture a screenshot of the full screen beforehand and then select from that. For that to be useful, whatever program was operating on the result of slurp would need to also use that screenshot. If you want to use grim for something like that I'd suggest taking a screenshot of the full screen then crop it in an image editor.

I think the second request for capturing a full window regardless of whether it is partially hidden, first of all, it is definitely out of scope, because that is a concern of the image capture program (for example grim) not slurp (which just gets coordiantes for a selected area). Secondly, it  would be difficult or impossible to do in wayland right now. especially in a compositor agnostic way, because afaik, there isn't any sort of protocol, standardized or not, to get a screenshot that includes the hidden area of a screen. The best you could probably do would be to focus the window, take the screenshot, and then unfocus it.
