### ISSUE TITLE
Is it possible to make slurp not steal focus from other windows?

### ISSUE THREAD

**Issue by artheus** [emersion/slurp#104]
I really like to use the slurp+grim combination for screenshots. However slurp always steals the focus from the currently active window, which some times make the active window dim, or otherwise change appearance.

This becomes quite irritable when you want your screenshots to look as if the current window is still active.

Is there any way to achieve this? Either by some inline command or code change?

**Comment by emersion** [comment]
No, that's not possible.

**Comment by deifactor** [comment]
You could:

- Use grim to screenshot the entire output
- Display it on top of everything else (not sure if there's a program for this)
- Use slurp to select the area
- Crop the original screenshot to that area using imagemagick or whatever

The tool for step 2 is the only thing I'm not sure if it exists, and slurp could have a `--background-image` flag (or whatever) to obviate it. Would be understandable if that was beyond scope, though.

IIRC this is what greenshot (the tool i use on Windows) does; if you're playing a video or whatever, when you screenshot a region the entire screen freezes.

**Comment by tmccombs** [comment]
I've created a WIP PR to try implement @deifactor's suggestion in #113.

See also the dicussion on #43

**Comment by lbatalha** [comment]
@deifactor I have implemented this in Sway as a script using `grim`, `slurp`, `swayimg`, `ffmpeg`, `wl-clipboard`

Example script:
```sh
#!/usr/bin/env bash
# requirements: sway, grim, slurp, swayimg, ffmpeg, wl-clipboard, swappy
# Freezes the screen, allows capturing an area.
# first argument: path to temporary file
# second argument: the classname to use for swayimg
#
# In sway config add:
# `for_window [app_id="swayimg-screenshot"] fullscreen enable global`
# to ensure that fullscreen spans all outputs
# alternatively, use swaymsg to set that in this script based on IMGCLASS
#
# Configure DESKTOPSIZE variable to match your total desktop size


TMPIMG=${1:-"/tmp/ss.tmp"}
IMGCLASS=${2:-"swayimg-screenshot"}
SLURPARG="-f %w:%h:%x:%y -d -b 00000066"
DESKTOPSIZE="0,0 11520x4320"

grim -c -t png -l 0 -s 1 -g "$DESKTOPSIZE" "$TMPIMG"
swayimg -b none -s real -c "$IMGCLASS" -n "$TMPIMG" &

(ffmpeg -loglevel warning -i "$TMPIMG" -vf "crop=$(slurp $SLURPARG)" -y \
        -c:v png -f image2pipe -pred 2 -compression_level 1 - ; \
        swaymsg -q "[app_id=$IMGCLASS] focus; kill" 1>&2) \
| swappy -f - -o - \
| wl-copy

rm "$TMPIMG"
```

Some details:

I used `ffmpeg` specifically because with my testing it was the fastest streaming png encoder, its faster than imagemagick `convert` and twice as fast as `grim` at minimum compression. (`grim` takes 0.4 seconds to screenshot and encode an image of my desktop with no compression, and 1.4s with level 1 compression, `grim` + `ffmpeg` together take 0.8s for the same content)
Unfortunately `swayimg` does not support `ppm`, as `grim` takes half the time to encode a `ppm` and `jpeg` vs `png`, and `jpeg` has noticeably lower quality due to 420 subsampling ([there is a PR to fix this](https://lists.sr.ht/~emersion/grim-dev/patches/37472))

You can easily replace `ffmpeg` with anything you want like `pngquant` and `convert`:


`swayimg` was picked because it allows me to override the `app_id`, so I can apply a global fullscreen and then kill the viewer easily. I could not find an easy way to override an application's `app_id` at runtime and the other solution is to dedicate a particular image viewer for this task. (it also just so happens that `swayimg` is quite lightweight and fast)

`swappy` is optional, and honestly something like it with a few tweaks would be the best way to replace `flameshot`, right now with `swappy`, if the UI borders could be removed and a crop feature added, it would be 90% of the way there, replacing this whole thing. It is unclear to me if `slurp` should be the one to implement this at all, it seems counterproductive if you don't want to annotate the image after (doubt `slurp` would get that much feature creep), when this script can do the same job by removing `swappy`.
https://github.com/jtheoof/swappy/issues/55


With some simple extra logic this script can be expanded to have options to capture outputs, windows, etc., but I only use area selection. If you `slurp` , `swappy` will show you the full desktop area anyway.

**Comment by apprehensions** [comment]
I've decided to make [wfreeze](https://codeberg.org/sewn/wfreeze), a bare-bones wayland program that helps solve this issue outside of grim and slurp, since it is out of scope for them.

It can be used like so:
```
wfreeze slurp | grim
```
and vice versa.

**Comment by emersion** [comment]
There is also https://codeberg.org/vyivel/dulcepan

**Comment by apprehensions** [comment]
While dulcepan has neat features like being able to redo selection, it cannot be configured to select windows like slurp's `slurp -r` option can. It is planning to do it's own protocol which compositors *have* to support for window selection.

**Comment by lbatalha** [comment]
> I've decided to make [wfreeze](https://codeberg.org/sewn/wfreeze), a bare-bones wayland program that helps solve this issue outside of grim and slurp, since it is out of scope for them.

Beautiful, this is just what I wanted, self-contained screen freeze utility that uses wlr-screencopy and wlr-layer-shell so that it is high quality _and_ high performance, thank you!
