### ISSUE TITLE
Input region labels

### ISSUE THREAD

**Issue by emersion** [emersion/slurp#58]
This would allow users to avoid the need to perform intersection checks themselves on the coords printed by slurp.

1. Add the ability to label regions provided on stdin, e.g. `0,0 42x42 @top-left`
2. Add a format specifier to print the selected input region label on stdout, e.g. `-f "%l"`

For instance, when selecting a Sway window, users could provide a label with the container ID, and make slurp print container IDs.

**Comment by RPigott** [comment]
This is a great feature, and I hope slurp learns it!

That said, [here](https://gist.github.com/RPigott/a9a868174e82986d414129c8be31397b)'s how I've been doing "swayprop" with the current version of slurp, and I think it actually has an _advantage_ over the suggested input labels. I don't allow slurp to parse the input "labels", so they can contain spaces or other complex output formats. Since slurp reads the input geometries from stdin, it would be nice if it also supported a way to set the input delimiter to newlines or allowed quoted labels so that it would be possible to set input labels containing spaces using this feature. I don't think I would use this feature otherwise, in favor of the bash script.

One way this could be implemented that would be an improvement is if you could have multiple tags. Then maybe `0,0 42x42 @con_id:5 @app_id:myapp @shell:xwayland` could be the input and the output format would probably be similar like `-f "@app_id (@shell)"`.

**Comment by emersion** [comment]
>set the input delimiter to newlines

Isn't the delimiter a newline already?

>allowed quoted labels

Or just read the label till end of line? I'm worried about clients not getting quoting right.

>One way this could be implemented that would be an improvement is if you could have multiple tags.

Why not pass directly `myapp (xwayland)` as a label to slurp?

**Comment by RPigott** [comment]
> Why not pass directly myapp (xwayland) as a label to slurp?

That's the goal.

> Isn't the delimiter a newline already?

Well newline works but this also works for me: `echo '0,0 960x1080 960,0 960x1080' | slurp` to split my screen into two selections, no newline.

I was thinking that if you wanted to label those and try: `echo '0,0 960x1080 @left 960,0 960x1080 @right' | slurp` how should it be parsed?

>  just read the label till end of line?

So what you're saying is the above should result in one region labelled "left 960,0 960x1080 @right"? I think that's fine. I just wasn't sure if you wanted it to be possible to specify multiple labelled regions in one line just as you can specify multiple unlabelled regions in one line.

My suggestion was an option to use newline as the only delimiter specifically so I could get the above behavior, but if you think it should always work that way that's even better as far as I'm concerned.

**Comment by emersion** [comment]
Hmm, weird. This sscanf call is supposed to search for a newline: https://github.com/emersion/slurp/blob/24d30b74d8063659c22abbde6aea34a03e467aa6/main.c#L753

**Comment by RPigott** [comment]
Huh. I guess _all_ white-space characters match any sequence of any white-space character in scanf.

`man 3 scanf`:

> The **format** string consists of a sequence of **directives** which describe how to process the sequence of input characters. [...] A directive is one of the following:
> - A sequence of white-space characters (space, tab, newline, etc.; see isspace(3)).  This directive matches **any amount of white space**, including none, in the input.

How unusual. I don't see how to get it to match a literal newline either.

Well, if it's unintentional behavior I wouldn't worry too much about breaking it.

**Comment by emersion** [comment]
Interesting. Yeah, I'm not worried about making slurp more strict in this regard.

**Comment by emersion** [comment]
f8eb0b87d305 makes slurp more strict.
